2024-11-29 00:10:38,025 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504485ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 00:19:43,024 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505187ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 00:28:48,024 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505357ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 00:37:53,029 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504382ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 00:46:58,025 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505182ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 00:56:03,025 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505187ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 01:05:08,021 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505186ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 01:14:13,028 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505415ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 01:23:18,031 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504229ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 01:32:37,027 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 379112ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 01:41:42,023 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505246ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 01:50:47,030 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505261ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 01:59:52,023 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505223ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 02:08:57,025 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505113ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 02:18:02,213 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505434ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 02:27:07,188 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505295ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 02:36:12,028 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505075ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 02:45:17,024 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505310ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 02:54:22,028 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505323ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 03:03:27,026 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505353ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 03:12:32,023 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505383ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 03:21:37,176 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505542ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 03:30:42,026 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505423ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 03:39:47,185 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505150ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 03:48:52,032 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505170ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 03:57:57,029 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505633ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 04:07:02,019 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504595ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 04:16:07,031 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504490ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 04:25:12,020 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504489ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 04:34:17,238 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504631ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 04:43:22,027 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504463ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 04:52:27,020 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504681ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 05:01:32,030 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504701ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 05:10:37,021 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504499ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 05:19:42,025 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505675ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 05:28:47,179 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504499ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 05:37:52,034 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505399ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 05:46:57,029 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504515ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 05:56:02,175 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504835ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 06:05:07,025 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 506402ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 06:14:12,191 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 502885ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 06:23:17,027 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504298ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 06:32:22,033 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 06:41:27,176 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504650ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 06:50:32,022 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504363ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 06:59:37,160 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 505676ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 07:08:42,026 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 07:17:47,040 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504574ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 07:26:52,029 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504402ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 07:35:57,185 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504733ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 07:45:02,028 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 504436ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 07:49:32,026 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 229582ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 08:19:40,392 ERROR 49546 [-/::1/-/44ms POST /api/getCdr/get] nodejs.SequelizeDatabaseError: Unknown column 'cdrs.remark' in 'where clause'
    at Query.run (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MySQLQueryInterface.rawSelect (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:434:18)
    at async cdrs.aggregate (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1277:19)
    at async cdrs.count (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1306:20)
    at async Promise.all (index 0)
    at async cdrs.findAndCountAll (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1322:27)
    at async AsteriskCdr.findAndCountAllByUid (/Users/Rodrigo/development/github/vozbox-work-server/app/service/asterisk_cdr.js:140:20)
    at async AsteriskCdr.index (/Users/Rodrigo/development/github/vozbox-work-server/app/controller/asterisk_cdr.js:42:22)
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'cdrs.remark' in 'where clause'","sql":"SELECT count(*) AS `count` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`remark` LIKE '%undefined%';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'cdrs.remark' in 'where clause'","sql":"SELECT count(*) AS `count` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`remark` LIKE '%undefined%';"}
sql: "SELECT count(*) AS `count` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`remark` LIKE '%undefined%';"
parameters: {}
pid: 49546
hostname: 115.115.0.179.static-mumbai.tcl.net.in

2024-11-29 08:20:06,593 ERROR 49546 [-/::1/-/53ms POST /api/getCdr/get] nodejs.SequelizeDatabaseError: Unknown column 'cdrs.remark' in 'where clause'
    at Query.run (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MySQLQueryInterface.rawSelect (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:434:18)
    at async cdrs.aggregate (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1277:19)
    at async cdrs.count (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1306:20)
    at async Promise.all (index 0)
    at async cdrs.findAndCountAll (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1322:27)
    at async AsteriskCdr.findAndCountAllByUid (/Users/Rodrigo/development/github/vozbox-work-server/app/service/asterisk_cdr.js:140:20)
    at async AsteriskCdr.index (/Users/Rodrigo/development/github/vozbox-work-server/app/controller/asterisk_cdr.js:42:22)
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'cdrs.remark' in 'where clause'","sql":"SELECT count(*) AS `count` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`remark` LIKE '%undefined%';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'cdrs.remark' in 'where clause'","sql":"SELECT count(*) AS `count` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`remark` LIKE '%undefined%';"}
sql: "SELECT count(*) AS `count` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`remark` LIKE '%undefined%';"
parameters: {}
pid: 49546
hostname: 115.115.0.179.static-mumbai.tcl.net.in

2024-11-29 09:11:17,055 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 619286ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 11:50:24,039 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 7846067ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 12:50:42,049 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 3537937ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 15:10:36,053 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 8353784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 16:41:17,166 ERROR 27020 nodejs.ClusterClientNoResponseError: client no response in 5439817ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 27020
hostname: CEREBRUM.local

2024-11-29 17:27:59,923 ERROR 52228 [-/::1/-/72ms POST /api/getCdr/get] nodejs.SequelizeDatabaseError: Unknown column 'uid' in 'field list'
    at Query.run (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MySQLQueryInterface.select (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async cdrs.findAll (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1140:21)
    at async Promise.all (index 1)
    at async cdrs.findAndCountAll (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1322:27)
    at async AsteriskCdr.findAndCountAllByUid (/Users/Rodrigo/development/github/vozbox-work-server/app/service/asterisk_cdr.js:140:20)
    at async AsteriskCdr.index (/Users/Rodrigo/development/github/vozbox-work-server/app/controller/asterisk_cdr.js:43:22)
    at async /Users/Rodrigo/development/github/vozbox-work-server/app/middleware/user_required.js:17:18
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'uid' in 'field list'","sql":"SELECT `uniqueid`, `uid`, `calldate`, `src`, `dst`, `userfield` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`dst` LIKE '%%' AND `cdrs`.`disposition` LIKE '%%' ORDER BY `cdrs`.`calldate` ASC LIMIT 0, 50;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'uid' in 'field list'","sql":"SELECT `uniqueid`, `uid`, `calldate`, `src`, `dst`, `userfield` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`dst` LIKE '%%' AND `cdrs`.`disposition` LIKE '%%' ORDER BY `cdrs`.`calldate` ASC LIMIT 0, 50;"}
sql: "SELECT `uniqueid`, `uid`, `calldate`, `src`, `dst`, `userfield` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`dst` LIKE '%%' AND `cdrs`.`disposition` LIKE '%%' ORDER BY `cdrs`.`calldate` ASC LIMIT 0, 50;"
parameters: {}
pid: 52228
hostname: 115.115.0.179.static-mumbai.tcl.net.in

2024-11-29 17:28:06,215 ERROR 52228 [-/::1/-/14ms POST /api/getCdr/get] nodejs.SequelizeDatabaseError: Unknown column 'uid' in 'field list'
    at Query.run (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MySQLQueryInterface.select (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async cdrs.findAll (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1140:21)
    at async Promise.all (index 1)
    at async cdrs.findAndCountAll (/Users/Rodrigo/development/github/vozbox-work-server/node_modules/sequelize/lib/model.js:1322:27)
    at async AsteriskCdr.findAndCountAllByUid (/Users/Rodrigo/development/github/vozbox-work-server/app/service/asterisk_cdr.js:140:20)
    at async AsteriskCdr.index (/Users/Rodrigo/development/github/vozbox-work-server/app/controller/asterisk_cdr.js:43:22)
    at async /Users/Rodrigo/development/github/vozbox-work-server/app/middleware/user_required.js:17:18
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'uid' in 'field list'","sql":"SELECT `uniqueid`, `uid`, `calldate`, `src`, `dst`, `userfield` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`dst` LIKE '%%' AND `cdrs`.`disposition` LIKE '%%' ORDER BY `cdrs`.`calldate` DESC LIMIT 0, 50;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'uid' in 'field list'","sql":"SELECT `uniqueid`, `uid`, `calldate`, `src`, `dst`, `userfield` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`dst` LIKE '%%' AND `cdrs`.`disposition` LIKE '%%' ORDER BY `cdrs`.`calldate` DESC LIMIT 0, 50;"}
sql: "SELECT `uniqueid`, `uid`, `calldate`, `src`, `dst`, `userfield` FROM `cdrs` AS `cdrs` WHERE (DATE(`calldate`) <= '2024-11-30' AND DATE(`calldate`) >= '2024-01-01') AND `cdrs`.`dst` LIKE '%%' AND `cdrs`.`disposition` LIKE '%%' ORDER BY `cdrs`.`calldate` DESC LIMIT 0, 50;"
parameters: {}
pid: 52228
hostname: 115.115.0.179.static-mumbai.tcl.net.in

