2024-11-20 00:00:03,937 INFO 83621 [egg-logrotator] agent logger reload: got log-reload message
2024-11-20 00:22:20,023 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 1313992ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 04:39:43,185 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 14542712ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 08:42:13,019 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 14429777ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 09:23:01,023 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 2409227ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 09:41:22,022 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 1060813ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 09:58:17,203 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 974954ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 10:52:44,022 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 3186785ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 11:41:51,052 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 2906815ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 12:21:58,166 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 2346783ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 14:22:43,056 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 7205313ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 18:25:39,188 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 14495931ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

2024-11-20 18:57:44,041 ERROR 83621 nodejs.ClusterClientNoResponseError: client no response in 1885046ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/Rodrigo/development/github/tomato-work-server/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
name: "ClusterClientNoResponseError"
pid: 83621
hostname: CEREBRUM.local

